// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ef9c5c1d-3c90-469e-b941-578eb841642f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_p7FglFVCW",
    "aws_user_pools_web_client_id": "10h1f3bpgqddid5o7vn44vj36b",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminModule",
            "endpoint": "https://tzgwqws8nc.execute-api.us-west-2.amazonaws.com/prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
